name: Deploy to gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^10"

      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
        with: # optional
          git-base-folder: ""
