name: Test Build

on:
  pull_request:
    branches: [dev, staging, master]

jobs:
  build:
    if: github.head_ref != 'master' && github.head_ref != 'staging' && github.head_ref != 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^10"

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: upload to s3
        if: |
          env.BRANCH_NAME != 'master' &&
          env.BRANCH_NAME != 'staging'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: staging-fiatswap-website
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEFAULT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEFAULT_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DEST_DIR: ${{ env.BRANCH_NAME }}
